/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface RogCons {
  value: number
  values: Array<number>
  text: string
  boolean: boolean
}
export function parse(input: string, attrMap: Record<string, number>): RogCons | null
